export * from './WebSpeech/index.js';
export * from './SpeechServer/index.js';
export * from './Fallback/index.js';
export * from '@readium/decorator';
export * from './decorator/index.js';
export { Locator, LocatorLocations, LocatorText } from '@readium/shared';
export { chineseVariantMap } from './voices/languages.js';
export * from './voices/types.js';
export * from './engine.js';
export * from './navigator.js';
export * from './provider.js';
export * from './providerRegistry.js';
export * from './speechNavigator.js';
export * from './utterance.js';
export * from './utterances/index.js';
export * from './preferences/index.js';
