import { ReadiumSpeechPlaybackEngine } from '../engine';
import { ReadiumSpeechNavigator, ReadiumSpeechPlaybackEvent, ReadiumSpeechPlaybackState } from '../navigator';
import { ReadiumSpeechUtterance } from '../utterance';
import { ReadiumSpeechVoice } from '../voices';
export declare class WebSpeechReadAloudNavigator implements ReadiumSpeechNavigator {
    private engine;
    private contentQueue;
    private eventListeners;
    private navigatorState;
    constructor(engine?: ReadiumSpeechPlaybackEngine);
    private initializeEngine;
    private setupEngineListeners;
    private setNavigatorState;
    getVoices(): Promise<ReadiumSpeechVoice[]>;
    setVoice(voice: ReadiumSpeechVoice | string): Promise<void>;
    getCurrentVoice(): ReadiumSpeechVoice | null;
    loadContent(content: ReadiumSpeechUtterance | ReadiumSpeechUtterance[]): void;
    getCurrentContent(): ReadiumSpeechUtterance | null;
    getContentQueue(): ReadiumSpeechUtterance[];
    private getCurrentUtteranceIndex;
    play(): void;
    pause(): void;
    stop(): void;
    private skipToPosition;
    next(forcePlay?: boolean): boolean;
    previous(forcePlay?: boolean): boolean;
    jumpTo(utteranceIndex: number, forcePlay?: boolean): boolean;
    setRate(rate: number): void;
    getRate(): number;
    setPitch(pitch: number): void;
    getPitch(): number;
    setVolume(volume: number): void;
    getVolume(): number;
    getState(): ReadiumSpeechPlaybackState;
    on(event: ReadiumSpeechPlaybackEvent["type"] | "contentchange", listener: (event: ReadiumSpeechPlaybackEvent) => void): () => void;
    private emitEvent;
    private emitContentChangeEvent;
    destroy(): Promise<void>;
}
